
export const Data =
[
    {
        "id" : "1",
        "image" :"/assets/PizzaPaperoni.png",
        "name": "Pizza paperoni",
        "category": "Pizza",
        "color" : "#E6F3F5",
        "icon" : "src/assets/asset/star4.png"
        
    },
    {
        "id" : "2",
        "image" :"src/assets/asset/PizzaMeat.png",
        "name": "Pizza paperoni",
        "category": "Pizza",
        "color" : "#E6F3F5",
        "icon" : "src/assets/asset/star3.png"
        
    },
    {
        "id" : "3",
        "image" :"./src/assets/asset/DonerKebab.png",
        "name": "Doner Kebab",
        "category": "kebab",
        "color" : "#EAEEFA",
        "icon" : "src/assets/asset/star5.png"
    },
    {
        "id" : "4",
        "image" :"src/assets/asset/SalmonRoll.png",
        "name": "Salmon Roll",
        "category": "Salmon",
        "color" : "#F9EEF3",
        "icon" : "src/assets/asset/star4.png"
    },
    {
        "id" : "5",
        "image" :"src/assets/asset/CupcakeCoco.png",
        "name": "Cupcake Coco",
        "category": "Cupcake",
        "color" : "#F0FEEB",
        "icon" : "src/assets/asset/star4.png"
    },
    {
        "id" : "6",
        "image" :"src/assets/asset/DoughnutMilk.png",
        "name": "Doughnut Milk",
        "category": "Doughnut",
        "color" : "#F3F7D9",
        "icon" : "src/assets/asset/star5.png"
    },
    {
        "id" : "7",
        "image" :"src/assets/asset/DoughnutUnicorn.png",
        "name": "Doughnut Unicorn",
        "category": "Doughnut",
        "color" : "#F3F7D9",
        "icon" : "src/assets/asset/star4.png"
    },
    {
        "id" : "8",
        "image" :"src/assets/asset/KathiKebab.png",
        "name": "Kathi Kebab",
        "category": "Kebab",
        "color" : "#EAEEFA",
        "icon" : "src/assets/asset/star4.png"
    }
]


